### ISSUE TITLE
Switch to node 16

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps-tiresias#110]
https://github.com/unil-lettres/dilps-tiresias/commit/8ad3a3da5fda47c124afaa25826a6c2ba5e45ab2#r80606563

**Comment by PowerKiKi** [comment]
C'est juste que j'ai upgradé le typing de node à la v16. Cependant [Angular supporte toujours node 14](https://github.com/angular/angular/blob/0abb67af59a92a2b29082a259aa9f4ea3fbaab7d/package.json#L11). Si c'est une bonne idée de migrer, parce que la [v14 est bientôt EOL](https://nodejs.org/en/about/releases/), c'est IMHO pas totalement urgentissime non plus.

**Comment by lucaguindani** [comment]
Solved by 23eb181506c1c12338dea6de91d056e0112ccfab
