### ISSUE TITLE
Gallery - lazy loading

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps-tiresias#41]
Sometimes the gallery's lazy loading feature will not stop loading new items (infinite loop until the page is reloaded).

**Comment by sambaptista** [comment]
Normalement c'est réglé par la mise à jour des libs relatives à la natural-gallery-js. 

Je propose de laisser ce ticket ouvert pour ne pas l'oublier mais de ne pas investir d'avantage d'énergie à chercher le soucis pour l'instant. Attendons de voir si ca se reproduit sur le staging de dev qui sera mis à jour dès que nous aurons qqch de stable et à jour.

**Comment by lucaguindani** [comment]
Je ne suis plus tombé sur ce soucis depuis la mise à jour de natural-gallery-js.
