### ISSUE TITLE
Public collections in funds

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps-tiresias#55]
When you select the funds they appears but also the list of public collections.

**Comment by sambaptista** [comment]
A priori, le problème a été résolu "tout seul" sur la nouvelle version. A voir avec les vrai données sur votre stating de test.

![capture 2019-11-15 at 14 15 51](https://user-images.githubusercontent.com/5111137/68946253-c9d56500-07b2-11ea-854e-423b3e1b64e8.png)

![capture 2019-11-15 at 14 15 55](https://user-images.githubusercontent.com/5111137/68946258-cc37bf00-07b2-11ea-8f69-78066fbf2100.png)

**Comment by lucaguindani** [comment]
Ok c'est noté, je regarde ca durant les tests en staging.

**Comment by lucaguindani** [comment]
Dans la nouvelle version les collections n'apparaissent plus dans la liste des fonds.
